version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=backend/app.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - ./src/backend:/app/backend
      - ./src/frontend:/app/frontend
